draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text_transformed_color(200, 100, "LEGACY OF MAGIC", 2.7, 2.7, 0, c_purple,c_purple,c_purple,c_purple,alphaval)
draw_text_transformed_color(200, 200, "by: Arthur Soong, Drake Norman,\nand Abhishek Acharya", 0.75, 0.75, 0, c_aqua, c_aqua, c_aqua, c_aqua, alphaval)
draw_set_halign(fa_left)
draw_set_valign(fa_top)