draw_text_transformed_color(10, 10, "For countless generations your family has \npracticed and perfected the art of magic,\nbut now people with knives and guns want\nto kill you and take that magic for\nthemselves, you must kill them first and\nprotect your family's ", 1, 1, 0, c_white,c_white,c_white,c_white,alphavalue)
draw_text_transformed_color(210, 111, "LEGACY", 1.5, 1.5, 0, c_red, c_red, c_red, c_red, alphavalue)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text_transformed_color(200, 200, "Press space to continue", 1, 1, 0, c_aqua, c_aqua, c_aqua, c_aqua, alphavalue)
draw_set_halign(fa_left)
draw_set_valign(fa_top)